/**
 * game obj
 */

declare type uobj = {
    [key: string]: any
    id?: string
    _parent?: string
    Art?: string
    file?: string
    Tip?: string
    HP?: any
    def?: any
    dmgplus1?: string
    STR?: string
    AGI?: string
    INT?: string
    STRplus?: string
    AGIplus?: string
    INTplus?: string
    weapsOn?: string
    Primary?: "STR" | "AGI" | "INT"
    movetp?: string
    Upgrade?: string
    fused?: string
    Sellitems?: string
    Sellunits?: string
    fmade?: string
    cool1?: string
    collision?: string
    bountyplus?: string
    cool2?: string
    abilList?: string
    manaN?: string
    Ubertip?: string
    Buttonpos_1?: string
    Buttonpos_2?: string
    Hotkey?: string
    Requires?: string
    heroAbilList?: string
    repulse?: string
    hostilePal?: string
    minSpd?: string
    spd?: string
    level?: string
    defUp?: string
    bldtm?: string
    splashTargs1?: string
    targType?: string
    splashTargs2?: string
    dmgpt2?: string
    Propernames?: string
    fogRad?: string
    maxSpd?: string
    goldRep?: string
    stockRegen?: string
    impactSwimZ?: string
    MissileHoming_1?: string
    MissileHoming_2?: string
    dmgpt1?: string
    buildingShadow?: string
    dropItems?: string
    Farea2?: string
    Trains?: string
    Farea1?: string
    shadowOnWater?: string
    Missileart_2?: string
    lumbercost?: string
    launchZ?: string
    acquire?: string
    launchY?: string
    launchX?: string
    maxRoll?: string
    Qarea2?: string
    Missileart_1?: string
    hideOnMinimap?: string
    Qarea1?: string
    weapType2?: string
    weapType1?: string
    animProps?: string
    Missilearc_2?: string
    Missilearc_1?: string
    Missilespeed_1?: string
    atkType1?: string
    deathType?: string
    Missilespeed_2?: string
    blue?: string
    moveHeight?: string
    RandomSoundLabel?: string
    Specialart?: string
    targs1?: string
    targs2?: string
    cargoSize?: string
    run?: string
    bountysides?: string
    Name?: string
    buffRadius?: string
    red?: any
    weapTp1?: string
    atkType2?: string
    weapTp2?: string
    regenType?: string
    prio?: string
    Requirescount?: string
    Builds?: string
    backSw2?: string
    backSw1?: string
    repulsePrio?: string
    armor?: string
    campaign?: string
    Revivetip?: string
    nameCount?: string
    damageLoss2?: string
    regenHP?: string
    damageLoss1?: string
    unitSound?: string
    Revive?: string
    elevPts?: string
    defType?: string
    Researches?: string
    dice1?: string
    dice2?: string
    Boneprops?: string
    green?: string
    mana0?: string
    race?: string
    propWin?: string
    fatLOS?: string
    canBuildOn?: string
    Awakentip?: string
    moveFloor?: string
    special?: string
    repulseParam?: string
    teamColor?: string
    turnRate?: string
    Casterupgradeart?: string
    Makeitems?: string
    hideHeroDeathMsg?: string
    type?: string
    upgrades?: string
    pathTex?: string
    buffType?: string
    impactZ?: string
    sight?: string
    selCircOnWater?: string
    Requires2?: string
    spillDist2?: string
    Requires1?: string
    occH?: string
    canSleep?: string
    showUI1?: string
    hideHeroBar?: string
    showUI2?: string
    shadowH?: string
    Description?: string
    goldcost?: string
    maxPitch?: string
    formation?: string
    inEditor?: string
    shadowX?: string
    shadowY?: string
    isBuildOn?: string
    Hfact2?: string
    Hfact1?: string
    regenMana?: string
    lumberRep?: string
    shadowW?: string
    Casterupgradetip?: string
    orientInterp?: string
    Attachmentanimprops?: string
    modelScale?: string
    canFlee?: string
    useClickHelper?: string
    Casterupgradename?: string
    preventPlace?: string
    lumberbountysides?: string
    scaleBull?: string
    tilesetSpecific?: string
    selZ?: string
    repulseGroup?: string
    tilesets?: string
    DependencyOr?: string
    launchSwimZ?: string
    requirePlace?: string
    nbrandom?: string
    auto?: string
    sides2?: string
    sides1?: string
    dmgplus2?: string
    points?: string
    requireWaterRadius?: string
    Harea2?: string
    Harea1?: string
    Qfact1?: string
    Qfact2?: string
    reptm?: string
    BuildingSoundLabel?: string
    bountydice?: string
    elevRad?: string
    castbsw?: string
    minRange?: string
    targCount1?: string
    targCount2?: string
    spillRadius1?: string
    death?: string
    spillRadius2?: string
    blend?: string
    Targetart?: string
    scale?: string
    LoopingSoundFadeOut?: string
    Attachmentlinkprops?: string
    dmgUp1?: string
    dmgUp2?: string
    LoopingSoundFadeIn?: string
    nsight?: string
    uberSplat?: string
    lumberbountyplus?: string
    isbldg?: string
    RngBuff1?: string
    hideHeroMinimap?: string
    spillDist1?: string
    lumberbountydice?: string
    RngBuff2?: string
    fileVerFlags?: string
    stockStart?: string
    stockMax?: string
    rangeN1?: string
    nbmmIcon?: string
    rangeN2?: string
    MovementSoundLabel?: string
    ScoreScreenIcon?: string
    unitShadow?: string
    customTeamColor?: string
    EditorSuffix?: string
    walk?: string
    castpt?: string
}


declare type upobj = {
    [key: string]: string
    id?: string
    _parent?: string
    code4?: string
    code3?: string
    mod4?: string
    Art?: string
    code2?: string
    mod3?: string
    code1?: string
    mod2?: string
    global?: string
    Buttonpos_1?: string
    Buttonpos_2?: string
    goldmod?: string
    Name?: string
    lumberbase?: string
    base3?: string
    base4?: string
    base1?: string
    base2?: string
    goldbase?: string
    lumbermod?: string
    mod1?: string
    class?: string
    maxlevel?: string
    race?: string
    Requiresamount?: string
    Requires?: string
    timebase?: string
    Ubertip?: string
    effect1?: string
    effect2?: string
    effect3?: string
    effect4?: string
    inherit?: string
    Tip?: string
    timemod?: string
    EditorSuffix?: string
    Hotkey?: string

}

declare type bobj = {
    [key: string]: string
    id?: string
    _parent?: string
    Targetattach?: string
    Targetattach1?: string
    Targetattach2?: string
    Targetattach3?: string
    Missilearc?: string
    Targetattach4?: string
    Bufftip?: string
    Targetattach5?: string
    Spelldetail?: string
    isEffect?: string
    MissileHoming?: string
    EffectArt?: string
    Targetattachcount?: string
    Missilespeed?: string
    Missileart?: string
    Buffart?: string
    SpecialArt?: string
    race?: string
    Effectsoundlooped?: string
    TargetArt?: string
    Specialattach?: string
    EditorName?: string
    Buffubertip?: string
    LightningEffect?: string
    Effectsound?: string
    EditorSuffix?: string
    Effectattach?: string


}
declare type deobj = {
    [key: string]: string
    id?: string
    _parent?: string
    MMGreen?: string
    colorB?: string
    shadow?: string
    flyH?: string
    selectable?: string
    HP?: string
    fogRadius?: string
    pathTexDeath?: string
    Name?: string
    texID?: string
    pathTex?: string
    useMMColor?: string
    numVar?: string
    radius?: string
    targType?: string
    selSize?: string
    buildTime?: string
    cliffHeight?: string
    occH?: string
    texFile?: string
    MMRed?: string
    deathSnd?: string
    goldRep?: string
    armor?: string
    portraitmodel?: string
    selcircsize?: string
    canPlaceDead?: string
    maxPitch?: string
    maxRoll?: string
    lightweight?: string
    canPlaceRandScale?: string
    file?: string
    onCliffs?: string
    fogVis?: string
    MMBlue?: string
    minScale?: string
    lumberRep?: string
    UserList?: string
    maxScale?: string
    walkable?: string
    fixedRot?: string
    showInMM?: string
    useClickHelper?: string
    fatLOS?: string
    colorR?: string
    tilesetSpecific?: string
    repairTime?: string
    onWater?: string
    tilesets?: string
    EditorSuffix?: string
    colorG?: string
    category?: string


}

declare type dobj = {
    [key: string]: string
    id?: string
    _parent?: string
    MMGreen?: string
    shadow?: string
    maxPitch?: string
    showInFog?: string
    maxRoll?: string
    Name?: string
    pathTex?: string
    useMMColor?: string
    canPlaceRandScale?: string
    file?: string
    visRadius?: string
    onCliffs?: string
    vertG?: string
    numVar?: string
    MMBlue?: string
    ignoreModelClick?: string
    minScale?: string
    defScale?: string
    UserList?: string
    animInFog?: string
    vertB?: string
    soundLoop?: string
    floats?: string
    maxScale?: string
    selSize?: string
    walkable?: string
    fixedRot?: string
    showInMM?: string
    useClickHelper?: string
    vertR?: string
    MMRed?: string
    tilesetSpecific?: string
    onWater?: string
    tilesets?: string
    category?: string

}


declare type aobj = {
    [key: string]: string
    id?: string
    _parent?: string
    Missilearc?: string
    Researchubertip?: string
    EfctID?: string
    Rng?: string
    Buttonpos_1?: string
    Buttonpos_2?: string
    BuffID?: string
    Name?: string
    Unhotkey?: string
    HeroDur?: string
    MissileHoming?: string
    Researchhotkey?: string
    EffectArt?: string
    Targetattachcount?: string
    Missileart?: string
    Casterattachcount?: string
    ResearchArt?: string
    Order?: string
    item?: string
    Untip?: string
    Requires?: string
    TargetArt?: string
    CasterArt?: string
    priority?: string
    Researchbuttonpos_1?: string
    Ubertip?: string
    Area?: string
    Researchbuttonpos_2?: string
    Casterattach?: string
    Researchtip?: string
    Unubertip?: string
    Hotkey?: string
    Cast?: string
    targs?: string
    Targetattach?: string
    Areaeffectart?: string
    Art?: string
    Targetattach1?: string
    Targetattach2?: string
    Targetattach3?: string
    Targetattach4?: string
    Targetattach5?: string
    Orderon?: string
    Cool?: string
    hero?: string
    reqLevel?: string
    Cost?: string
    Unorder?: string
    DataF?: string
    DataG?: string
    UnButtonpos_2?: string
    DataH?: string
    DataI?: string
    DataB?: string
    UnButtonpos_1?: string
    DataC?: string
    DataD?: string
    DataE?: string
    Missilespeed?: string
    DataA?: string
    SpecialArt?: string
    Dur?: string
    levelSkip?: string
    race?: string
    Effectsoundlooped?: string
    Requiresamount?: string
    Specialattach?: string
    Unart?: string
    Orderoff?: string
    UnitID?: string
    LightningEffect?: string
    Effectsound?: string
    Tip?: string
    EditorSuffix?: string
    Animnames?: string
    checkDep?: string
    levels?: string

}


declare type iobj = {
    [key: string]: string
    id?: string
    _parent?: string
    drop?: string
    powerup?: string
    colorB?: string
    Art?: string
    Description?: string
    goldcost?: string
    HP?: string
    cooldownID?: string
    scale?: string
    lumbercost?: string
    sellable?: string
    Buttonpos_1?: string
    Buttonpos_2?: string
    Name?: string
    usable?: string
    file?: string
    oldLevel?: string
    prio?: string
    class?: string
    perishable?: string
    selSize?: string
    stockStart?: string
    Requires?: string
    stockMax?: string
    pawnable?: string
    Ubertip?: string
    droppable?: string
    ignoreCD?: string
    colorR?: string
    stockRegen?: string
    armor?: string
    abilList?: string
    Level?: string
    Tip?: string
    colorG?: string
    uses?: string
    morph?: string
    pickRandom?: string
    Hotkey?: string
}