local ____lualib = require("lualib_bundle")
local __TS__SourceMapTraceBack = ____lualib.__TS__SourceMapTraceBack
__TS__SourceMapTraceBack(debug.getinfo(1).short_src, {["5"] = 1,["6"] = 1,["7"] = 1,["8"] = 1,["9"] = 1,["10"] = 1,["11"] = 1,["12"] = 1,["13"] = 1,["14"] = 1,["15"] = 1,["16"] = 1,["17"] = 1,["18"] = 1,["19"] = 1,["20"] = 1,["21"] = 1,["22"] = 1,["23"] = 1,["24"] = 1,["25"] = 1,["26"] = 1,["27"] = 1,["28"] = 1,["29"] = 1,["30"] = 1,["31"] = 1,["32"] = 1,["33"] = 1,["34"] = 1,["35"] = 1,["36"] = 1,["37"] = 1,["38"] = 1,["39"] = 1,["40"] = 1,["41"] = 1,["42"] = 1,["43"] = 1,["44"] = 1,["45"] = 1,["46"] = 1,["47"] = 1,["48"] = 24});
local ____exports = {}
local WeatherEffects = WeatherEffects or ({})
WeatherEffects.ASHENVALE_HEAVY_RAIN = FourCC("RAhr")
WeatherEffects[WeatherEffects.ASHENVALE_HEAVY_RAIN] = "ASHENVALE_HEAVY_RAIN"
WeatherEffects.ASHENVALE_LIGHT_RAIN = FourCC("RAlr")
WeatherEffects[WeatherEffects.ASHENVALE_LIGHT_RAIN] = "ASHENVALE_LIGHT_RAIN"
WeatherEffects.DALARAN_SHIELD = FourCC("MEds")
WeatherEffects[WeatherEffects.DALARAN_SHIELD] = "DALARAN_SHIELD"
WeatherEffects.DUNGEON_BLUE_FOG_HEAVY = FourCC("FDbh")
WeatherEffects[WeatherEffects.DUNGEON_BLUE_FOG_HEAVY] = "DUNGEON_BLUE_FOG_HEAVY"
WeatherEffects.DUNGEON_BLUE_FOG_LIGHT = FourCC("FDbl")
WeatherEffects[WeatherEffects.DUNGEON_BLUE_FOG_LIGHT] = "DUNGEON_BLUE_FOG_LIGHT"
WeatherEffects.DUNGEON_GREEN_FOG_HEAVY = FourCC("FDgh")
WeatherEffects[WeatherEffects.DUNGEON_GREEN_FOG_HEAVY] = "DUNGEON_GREEN_FOG_HEAVY"
WeatherEffects.DUNGEON_GREEN_FOG_LIGHT = FourCC("FDgl")
WeatherEffects[WeatherEffects.DUNGEON_GREEN_FOG_LIGHT] = "DUNGEON_GREEN_FOG_LIGHT"
WeatherEffects.DUNGEON_RED_FOG_HEAVY = FourCC("FDrh")
WeatherEffects[WeatherEffects.DUNGEON_RED_FOG_HEAVY] = "DUNGEON_RED_FOG_HEAVY"
WeatherEffects.DUNGEON_RED_FOG_LIGHT = FourCC("FDrl")
WeatherEffects[WeatherEffects.DUNGEON_RED_FOG_LIGHT] = "DUNGEON_RED_FOG_LIGHT"
WeatherEffects.DUNGEON_WHITE_FOG_HEAVY = FourCC("FDwh")
WeatherEffects[WeatherEffects.DUNGEON_WHITE_FOG_HEAVY] = "DUNGEON_WHITE_FOG_HEAVY"
WeatherEffects.DUNGEON_WHITE_FOG_WEAK = FourCC("FDwl")
WeatherEffects[WeatherEffects.DUNGEON_WHITE_FOG_WEAK] = "DUNGEON_WHITE_FOG_WEAK"
WeatherEffects.LORDAERON_HEAVY_RAIN = FourCC("RLhr")
WeatherEffects[WeatherEffects.LORDAERON_HEAVY_RAIN] = "LORDAERON_HEAVY_RAIN"
WeatherEffects.LORDAERON_LIGHT_RAIN = FourCC("RLlr")
WeatherEffects[WeatherEffects.LORDAERON_LIGHT_RAIN] = "LORDAERON_LIGHT_RAIN"
WeatherEffects.NORTHREND_BLIZZARD = FourCC("SNbs")
WeatherEffects[WeatherEffects.NORTHREND_BLIZZARD] = "NORTHREND_BLIZZARD"
WeatherEffects.NORTHREND_HEAVY_SNOW = FourCC("SNhs")
WeatherEffects[WeatherEffects.NORTHREND_HEAVY_SNOW] = "NORTHREND_HEAVY_SNOW"
WeatherEffects.NORTHREND_LIGHT_SNOW = FourCC("SNls")
WeatherEffects[WeatherEffects.NORTHREND_LIGHT_SNOW] = "NORTHREND_LIGHT_SNOW"
WeatherEffects.RAYS_OF_LIGHT = FourCC("LRaa")
WeatherEffects[WeatherEffects.RAYS_OF_LIGHT] = "RAYS_OF_LIGHT"
WeatherEffects.RAYS_OF_MOONLIGHT = FourCC("LRma")
WeatherEffects[WeatherEffects.RAYS_OF_MOONLIGHT] = "RAYS_OF_MOONLIGHT"
WeatherEffects.WEATHER_WIND = FourCC("WNcw")
WeatherEffects[WeatherEffects.WEATHER_WIND] = "WEATHER_WIND"
WeatherEffects.WEATHER_OUTLAND_WIND = FourCC("WOcw")
WeatherEffects[WeatherEffects.WEATHER_OUTLAND_WIND] = "WEATHER_OUTLAND_WIND"
WeatherEffects.WEATHER_OUTLAND_WIND_LIGHT = FourCC("WOlw")
WeatherEffects[WeatherEffects.WEATHER_OUTLAND_WIND_LIGHT] = "WEATHER_OUTLAND_WIND_LIGHT"
____exports.default = WeatherEffects
return ____exports
